"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import type { ProjectSummary } from "@/lib/types";

const ACTIVE_PROJECT_KEY = "trident_active_project_id";
const stageLabels: Record<string, string> = { research_brief: "研究范围", research_planning: "研究规划", evidence_collection: "网页研究", evidence_qa: "证据审核", industry_analysis: "行业分析", future_intelligence: "未来判断", decision_report: "报告" };
function progress(project: ProjectSummary) { const states = Object.values(project.workflow_status || {}); return states.length ? Math.round(states.filter((item) => item === "completed").length / states.length * 100) : 0; }

function useLinkedProjects() {
  const [projects, setProjects] = useState<ProjectSummary[]>([]);
  const [activeId, setActiveIdState] = useState("");
  useEffect(() => { fetch("/api/projects", { cache: "no-store" }).then((r) => r.ok ? r.json() : []).then((rows: ProjectSummary[]) => { setProjects(rows); const saved = window.localStorage.getItem(ACTIVE_PROJECT_KEY); setActiveIdState(saved && rows.some((row) => row.project_id === saved) ? saved : (rows[0]?.project_id || "")); }).catch(() => setProjects([])); }, []);
  function setActiveId(id: string) { setActiveIdState(id); window.localStorage.setItem(ACTIVE_PROJECT_KEY, id); }
  return { projects, activeId, activeProject: projects.find((project) => project.project_id === activeId), setActiveId };
}

function LinkedContextBar({ projects, activeId, onChange }: { projects: ProjectSummary[]; activeId: string; onChange: (id: string) => void }) {
  const active = projects.find((project) => project.project_id === activeId);
  return <div className="linkedContext"><div><span>当前联动项目</span><strong>{active?.project_name || "尚未选择项目"}</strong><small>{active ? `${active.industry} · ${active.region} · ${stageLabels[active.current_step] || active.current_step}` : "先在项目管理中选择一个工作项目"}</small></div><select value={activeId} onChange={(event) => onChange(event.target.value)} aria-label="切换当前联动项目"><option value="">选择项目</option>{projects.map((project) => <option key={project.project_id} value={project.project_id}>{project.project_name}</option>)}</select><nav><Link href="/knowledge">知识库</Link><Link href="/sensing">持续感知</Link><Link href="/feedback">质量 Dashboard</Link>{active && <Link href={`/projects/${active.project_id}`}>研究工作台</Link>}</nav></div>;
}

export function WorkspaceHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <><header className="consultingTopbar"><div><span>TRIDENT AI</span><strong>Decision Intelligence Studio</strong></div><nav><Link href="/">场景选择</Link><Link href="/projects">项目管理</Link></nav></header><div className="platformPageHero"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></>;
}

export function ProjectManagementWorkspace() {
  const { projects, activeId, setActiveId } = useLinkedProjects(); const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all");
  const rows = useMemo(() => projects.filter((p) => `${p.project_name} ${p.industry} ${p.region}`.toLowerCase().includes(query.toLowerCase())).filter((p) => filter === "all" || (filter === "active" ? p.workflow_status.decision_report !== "completed" : p.workflow_status.decision_report === "completed")), [projects, query, filter]);
  return <main><WorkspaceHeader eyebrow="PROJECT PORTFOLIO" title="项目管理与场景切换" description="所有场景的工作独立保存，并在同一项目空间恢复、查找和继续。切换场景不会覆盖原项目。"/><section className="platformPage"><LinkedContextBar projects={projects} activeId={activeId} onChange={setActiveId}/><div className="projectToolbar"><div><button className={filter === "all" ? "selected" : ""} onClick={() => setFilter("all")}>全部项目</button><button className={filter === "active" ? "selected" : ""} onClick={() => setFilter("active")}>进行中</button><button className={filter === "done" ? "selected" : ""} onClick={() => setFilter("done")}>已完成</button></div><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索项目、行业或地区"/><Link className="primaryButton" href="/">新建场景项目</Link></div><div className="projectPortfolioGrid">{rows.map((project) => <article className={project.project_id === activeId ? "activeProject" : ""} key={project.project_id}><div className="projectMeta"><span>{project.scenario_pack || "general"}</span><small>{new Date(project.updated_at).toLocaleDateString("zh-CN")}</small></div><h2>{project.project_name}</h2><p>{project.industry} · {project.region}</p><div className="projectProgress"><span style={{width:`${progress(project)}%`}}/></div><footer><div><strong>{progress(project)}%</strong><small>{stageLabels[project.current_step] || project.current_step}</small></div><div className="projectActions"><button type="button" onClick={() => setActiveId(project.project_id)}>{project.project_id === activeId ? "当前联动项目" : "设为联动项目"}</button><Link href={`/projects/${project.project_id}`}>继续工作 →</Link></div></footer></article>)}{!rows.length && <div className="platformEmpty"><h2>没有符合条件的项目</h2><p>进入场景选择，建立第一个可持续恢复的决策项目。</p></div>}</div></section></main>;
}

const signals = [
  { type: "政策", title: "行业监管与准入规则出现更新", source: "政策与监管来源", time: "今日 09:40", impact: "需要复核市场边界与进入条件", level: "高影响" },
  { type: "竞争", title: "重点竞争者发布新产品与渠道合作", source: "公司公告 / 行业新闻", time: "昨日 18:20", impact: "可能改变机会优先级与竞争判断", level: "中影响" },
  { type: "客户", title: "下游客户采购周期和需求侧指标变化", source: "经营数据 / 客户反馈", time: "8月19日", impact: "关联收入假设与 Action Plan", level: "待评估" },
];

export function SensingWorkspace() {
  const { projects, activeId, activeProject, setActiveId } = useLinkedProjects(); const [signalFilter, setSignalFilter] = useState("全部"); const visibleSignals = signalFilter === "全部" ? signals : signals.filter((signal) => signal.type === signalFilter);
  return <main><WorkspaceHeader eyebrow="CONTINUOUS SENSING" title="持续感知与决策信号" description="自动采集新闻、政策、公司公告和经营变化；先判断与企业、项目和关键假设的关系，再决定是否触发研究或行动调整。"/><section className="platformPage"><LinkedContextBar projects={projects} activeId={activeId} onChange={setActiveId}/><div className="sensingSummary"><article><span>24</span><small>今日新增信号</small></article><article><span>7</span><small>已关联项目</small></article><article><span>3</span><small>高影响待复核</small></article><article><span>86%</span><small>去重与分类完成</small></article></div><div className="sensingLayout"><section className="signalFeed"><div className="sectionTitle"><div><span className="eyebrow">SIGNAL INBOX</span><h2>新闻与变化信号</h2></div><Link href="/projects">配置关注项目</Link></div><div className="signalFilters">{["全部","政策","竞争","客户","技术","经营 KPI"].map((item) => <button key={item} className={signalFilter === item ? "selected" : ""} onClick={() => setSignalFilter(item)}>{item}</button>)}</div>{visibleSignals.map((item) => <article className="signalRow" key={item.title}><span>{item.type}</span><div><h3>{item.title}</h3><p>{item.source} · {item.time}</p><strong>{item.impact}</strong></div><em>{item.level}</em></article>)}</section><aside className="impactPanel"><span className="eyebrow">IMPACT ROUTER</span><h2>从信号到决策动作</h2><ol><li><span>01</span><div><strong>抓取与去重</strong><small>新闻、政策、公告与内部数据</small></div></li><li><span>02</span><div><strong>实体与项目关联</strong><small>匹配企业、行业、假设和 Action Plan</small></div></li><li><span>03</span><div><strong>影响评估</strong><small>判断是否改变范围、Scorecard 或优先级</small></div></li><li><span>04</span><div><strong>人工复核后更新</strong><small>创建新版本，不覆盖已批准判断</small></div></li></ol><Link className="primaryButton linkButton" href={activeProject ? `/projects/${activeProject.project_id}` : "/projects"}>回到关联项目处理影响</Link></aside></div></section></main>;
}

export function KnowledgeWorkspace() { const { projects, activeId, activeProject, setActiveId } = useLinkedProjects(); return <main><WorkspaceHeader eyebrow="ENTERPRISE KNOWLEDGE BASE" title="企业知识库" description="场景之间共享经过授权和版本化的企业资产，但每个项目仍保留独立证据、判断和流程。"/><section className="platformPage"><LinkedContextBar projects={projects} activeId={activeId} onChange={setActiveId}/><div className="knowledgeEntity"><div><span>当前企业 / 标的</span><h2>{activeProject?.target_company || activeProject?.industry || "选择企业或投资标的"}</h2><p>{activeProject ? `${activeProject.project_name} 正在引用该实体的画像、经营事实、历史决策与行动结果。` : "先选择一个联动项目，系统会定位对应企业资产。"}</p></div><Link href="/projects">切换关联项目</Link></div><div className="platformCapabilityGrid"><article><span>01</span><h3>企业画像</h3><p>组织、产品、客户、渠道、资源与管理层决策风格。</p></article><article><span>02</span><h3>经营情况</h3><p>收入、利润、订单、交付和关键经营指标的时间化快照。</p></article><article><span>03</span><h3>历史决策</h3><p>目标、依据、被拒方案、责任人与当时的假设边界。</p></article><article><span>04</span><h3>结果与反馈</h3><p>Action Plan 进度、实际效果、偏差原因和调整记录。</p></article></div><div className="knowledgeTimeline"><h2>企业时间线</h2><p>{activeProject ? `当前显示 ${activeProject.project_name} 的关联资产。后续会按时间串联访谈、研究、决策、行动和结果反馈。` : "选择联动项目后显示企业时间线。"}</p></div></section></main>; }

export function FeedbackWorkspace() { const { projects, activeId, activeProject, setActiveId } = useLinkedProjects(); return <main><WorkspaceHeader eyebrow="DECISION & ACTION QUALITY" title="决策与行动质量 Dashboard" description="跨项目监测决策、计划设计和执行质量；具体反馈与动态调整仍发生在 PE、VC、企业增长各自的工作流内。"/><section className="platformPage"><LinkedContextBar projects={projects} activeId={activeId} onChange={setActiveId}/><div className="feedbackFlow">{[["01","决策质量","假设验证率、预测偏差与证据—结果一致性"],["02","行动质量","按期完成率、KPI 达成与计划有效性"],["03","执行质量","阻塞、责任人反馈、资源到位与完成证据"],["04","学习质量","反馈完整度、调整时延与重复错误率"]].map((item) => <article key={item[0]}><span>{item[0]}</span><h2>{item[1]}</h2><p>{item[2]}</p></article>)}</div><div className="feedbackBoard"><div><span className="eyebrow">SCENARIO-EMBEDDED FEEDBACK</span><h2>{activeProject ? `${activeProject.project_name} · 质量诊断` : "选择项目查看决策—行动—结果链路"}</h2><p>反馈入口位于场景项目的 Action Plan 或投后里程碑节点；Dashboard 只聚合并诊断，不静默改写已批准版本。</p></div><Link className="primaryButton linkButton" href={activeProject ? `/projects/${activeProject.project_id}` : "/projects"}>{activeProject ? "进入场景工作流" : "选择项目"}</Link></div></section></main>; }
